version: '3.8'

services:
  app:
    build: .
    ports:
      - 8080:8080
    volumes:
      - .:/go/src/app
    command: go run main.go DB_USER=docker DB_PASSWORD=docker DB_NAME=sampledb
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    platform: linux/x86_64
    command: 
        - --character-set-server=utf8mb4
        - --collation-server=utf8mb4_unicode_ci
        - --sql-mode=ONLY_FULL_GROUP_BY,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
    environment:
        MYSQL_ROOT_USER: ${ROOTUSER}
        MYSQL_ROOT_PASSWORD: ${ROOTPASS}
        MYSQL_DATABASE: ${DATABASE}
        MYSQL_USER: ${USERNAME}
        MYSQL_PASSWORD: ${USERPASS}
        TZ: 'Asia/Tokyo'
    ports: 
        - 3306:3306
    volumes:
        - db-volume:/var/lib/mysql
        - ./createTable.sql:/var/lib/mysql/createTable.sql
        - ./insertData.sql:/var/lib/mysql/insertData.sql

volumes:
  db-volume:
